### ISSUE TITLE
Сортировка вариантов с цветами в корзине в карточке товара

### ISSUE THREAD

**Issue by dapi** [BrandyMint/merchantly-public-js#74]
* [x] выводить цвета в корзине
* [x] drug-drop тваров в карточке товара

![6to_mywx5s4](https://user-images.githubusercontent.com/31139/27793799-2271235c-6008-11e7-9de0-0636908a15dc.jpg)

* [x] Опциональная сортировка товаров в корзине. Параметр устанавливается в баке на странице настройки заказа /operator/settings

Магазин: https://standart.kiiiosk.ru
Пример: http://ustyles.ru/catalog/product/21760/

**Comment by dapi** [comment]
Вот тут я удалил сортировку - https://github.com/BrandyMint/merchantly-public-js/commit/c21515c2466f0aa469e803b8a57ea00e5d07fc2f ее надо вернуть

**Comment by Bedunkevich** [comment]
Мы вроде все тут сделали, почему не закрыл issue?
